import { App, Button, Card, Form, Input, InputNumber, Modal, Select, Space, Table, Tabs, Tag } from 'antd'
import { CheckOutlined, CloseOutlined, PlusOutlined } from '@ant-design/icons'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import dayjs from 'dayjs'
import { api, patch, post } from '../api'
import type { User } from '../types'

export default function ReviewsPage({user}:{user:User}) {
  const [decision,setDecision]=useState<any|null>(null);const [mappingOpen,setMappingOpen]=useState(false)
  const [decisionForm]=Form.useForm();const [mappingForm]=Form.useForm();const client=useQueryClient();const {message}=App.useApp()
  const reviews=useQuery<any[]>({queryKey:['reviews'],queryFn:()=>api('/v1/reviews')})
  const mappings=useQuery<any[]>({queryKey:['mappings'],queryFn:()=>api('/v1/mappings')})
  const decide=useMutation({mutationFn:({id,body}:{id:number;body:any})=>patch(`/v1/reviews/${id}`,body),onSuccess:()=>{message.success('审核已提交');setDecision(null);client.invalidateQueries({queryKey:['reviews']})},onError:(e:Error)=>message.error(e.message)})
  const addMapping=useMutation({mutationFn:(body:any)=>post('/v1/mappings',body),onSuccess:()=>{message.success('映射已添加');setMappingOpen(false);client.invalidateQueries({queryKey:['mappings']})},onError:(e:Error)=>message.error(e.message)})
  const reviewTable=<Table rowKey="id" dataSource={reviews.data||[]} loading={reviews.isLoading} columns={[{title:'条目 ID',dataIndex:'item_id',render:(v:string)=><span className="mono">{v.slice(0,8)}</span>},{title:'字段',dataIndex:'field',render:(v:string)=><Tag>{v}</Tag>},{title:'建议值',dataIndex:'proposed_value'},{title:'置信度',dataIndex:'confidence',render:(v:number)=>`${Math.round(v*100)}%`},{title:'入队时间',dataIndex:'created_at',render:(v:string)=>dayjs(v).format('MM-DD HH:mm')},{title:'操作',render:(_:unknown,r:any)=><Space><Button size="small" type="primary" icon={<CheckOutlined/>} disabled={user.role!=='admin'} onClick={()=>{setDecision({...r,decision:'accepted'});decisionForm.setFieldsValue({decision:'accepted',value:r.proposed_value})}}>接受</Button><Button size="small" icon={<CloseOutlined/>} disabled={user.role!=='admin'} onClick={()=>{setDecision({...r,decision:'rejected'});decisionForm.setFieldsValue({decision:'rejected'})}}>拒绝</Button></Space>}]} />
  const mappingTable=<><div style={{textAlign:'right',marginBottom:12}}><Button icon={<PlusOutlined/>} disabled={user.role!=='admin'} onClick={()=>{mappingForm.resetFields();mappingForm.setFieldsValue({confidence:1,enabled:true});setMappingOpen(true)}}>新增映射</Button></div><Table rowKey="id" dataSource={mappings.data||[]} loading={mappings.isLoading} columns={[{title:'维度',dataIndex:'dimension_type'},{title:'来源原值',dataIndex:'raw_value'},{title:'规范值',dataIndex:'normalized_value'},{title:'置信度',dataIndex:'confidence',render:(v:number)=>`${Math.round(v*100)}%`},{title:'启用',dataIndex:'enabled',render:(v:boolean)=><Tag color={v?'green':'default'}>{v?'启用':'停用'}</Tag>}]} /></>
  return <><div className="page-head"><div><h1>数据审核</h1><p>处理低置信分类并维护可解释的跨站映射规则</p></div><Tag color="gold">阈值 80%</Tag></div><Card className="panel-card"><Tabs items={[{key:'reviews',label:`待审核 (${reviews.data?.length||0})`,children:reviewTable},{key:'mappings',label:'分类映射',children:mappingTable}]}/></Card><Modal title="分类审核" open={!!decision} onCancel={()=>setDecision(null)} onOk={()=>decisionForm.validateFields().then(body=>decide.mutate({id:decision.id,body}))}><Form form={decisionForm} layout="vertical"><Form.Item name="decision" label="决定"><Select options={[{value:'accepted',label:'接受并应用'},{value:'rejected',label:'拒绝'}]}/></Form.Item><Form.Item name="value" label="最终值"><Input/></Form.Item><Form.Item name="note" label="审核说明"><Input.TextArea rows={3}/></Form.Item></Form></Modal><Modal title="新增分类映射" open={mappingOpen} onCancel={()=>setMappingOpen(false)} onOk={()=>mappingForm.validateFields().then(v=>addMapping.mutate(v))}><Form form={mappingForm} layout="vertical"><Form.Item name="dimension_type" label="维度" rules={[{required:true}]}><Select options={['product_type','industry','region','object_kind','delivery_method'].map(value=>({value}))}/></Form.Item><Form.Item name="raw_value" label="来源原值" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="normalized_value" label="规范值" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="confidence" label="置信度"><InputNumber min={0} max={1} step={0.05}/></Form.Item></Form></Modal></>
}
